on: [push, pull_request]

jobs:
    build:
      name: Check
      runs-on: ubuntu-latest
      env:
        GO111MODULE: on

      steps:

        - name: Install libraries
          run: |
            sudo apt-get update
            sudo apt-get install -y libncurses5 libaio1 libnuma1 bash-completion
        - name: Set up Go 1.x
          uses: actions/setup-go@v2
          with:
            go-version: ^1.18

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: tests
          run: ./scripts/ci.sh
